### ISSUE TITLE
IF MARKS STOP SAVING, UPDATE THIS ISSUE

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/harpoon#68] opened 2021-05-05 20:05 UTC
Gotta make those marks save... This is annoying!

**Comment by ThePrimeagen** [comment] 2021-05-07 03:21
It happens intermittently.  I don't know when it happens.  I don't know how it happens.

If anyone can create a repo case, please let me know.  Also, please if you can run the repo case with trace debugging :)

**Comment by numine777** [comment] 2021-06-17 15:11
I'm noticing an issue with this.  Behavior summary: opening and closing neovim will retain marks, but after navigating to mark 1, other marks will drop.  Upon navigating to a previously marked file, the marks will repopulate (all 4 in my case).  I'll update this comment if behavior changes or if I notice anything related.

**Comment by ThePrimeagen** [comment] 2021-06-17 15:14
@numine777 if you are able to consistently reproduce this would you be willing to run it with Trace logging on?

**Comment by numine777** [comment] 2021-06-17 15:35
Absolutely!  I'll get back to you shortly

**Comment by numine777** [comment] 2021-06-17 15:43
[nvim.log](https://github.com/ThePrimeagen/harpoon/files/6671475/nvim.log)

**Comment by freehaha** [comment] 2021-08-22 02:07
Not sure if this is the same issue but because all instances of nvim uses the same file and autosave using the in-memory copy of the file so a second nvim instance can overwrite the changes saved in the first one, causing the saved marks for all other project to revert back to their original state when the nvim first load.

To solve this we can either reload config json(`harpoon.json`) before writing or have one file for each project (will still have this problem if there are multiple nvim instances for the same project but should be less of a problem for most cases).

Reproduce:
1. (proj1) cd proj1 && nvim -u ../init.nvim file1
1. (proj2) cd proj2 && nvim -u ../init.nvim file1
1. (proj1) add mark
1. (proj1) close nvim
1. (proj1) # cd proj1 && nvim -u ../init.nvim file1 # _marks should still be there_
1. (proj2) close nvim
1. (proj1) cd proj1 && nvim -u ../init.nvim file1
1. (proj1) **marks are gone**

init.vim:
```vim
filetype plugin indent on
" syntax on

call plug#begin('~/vimtest/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'ThePrimeagen/harpoon'
call plug#end()

let mapleader = "\<Space>"
nnoremap <leader>a :lua require("harpoon.mark").add_file()<cr>
nnoremap <c-e> :lua require("harpoon.ui").toggle_quick_menu()<cr>
lua <<LUA
require("harpoon").setup({
    global_settings = {
        save_on_toggle = false,
        save_on_change = true,
    };
})
LUA
```

file structure:
```
.
├── autoload
│   └── plug.vim
├── bug.md
├── init.vim
├── plugged
│   ├── harpoon
│   ├── plenary.nvim
│   └── popup.nvim
├── proj1
│   ├── .git
│   ├── file1
│   └── file2
└── proj2
    ├── .git
    ├── file1
    └── file2
```

**Comment by pranavrao145** [comment] 2021-09-01 16:01
Adding on to the issue with multiple instances of neovim running at once, for anyone that uses tmux with a plugin like [tmux-continuum](https://github.com/tmux-plugins/tmux-continuum) or [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect), you may run into an issue of your marks reverting back to a certain state after reboot or tmux server restart.

I had this problem, and it seems that the reason for it was because tmux-resurrect was restoring neovim processes in the background, which were also using harpoon. For that reason, there was some overlap writing to `harpoon.json` and marks were reverted back to a certain state, probably in relation to the problem @freehaha brought up.
 
I managed to solve this by adding this line to my tmux configuration:
`set -g @resurrect-processes 'false'`

That basically just disables tmux-resurrect from restoring processes like neovim when the tmux server starts. That way, no random neovim processes are started in the background and harpoon works perfectly because it's only dealing with one project at a time. Hopefully this can help someone else that is facing a similar/the same problem.

**Closed** 2021-12-02 15:57 UTC
