### ISSUE TITLE
Harpoon list persistence [harpoon2]

### ISSUE THREAD

**Issue by yobibyte** [ThePrimeagen/harpoon#343] opened 2023-11-30 23:57 UTC
I'm running harpoon2 with the suggested config installing with Lazy on MacOS 12.6. 

```lua
{
  "ThePrimeagen/harpoon",
  branch="harpoon2",
  config = function()
    local harpoon = require("harpoon");
    vim.keymap.set("n", "<leader>ha", function() harpoon:list():append() end)
    vim.keymap.set("n", "<C-e>", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end)
    vim.keymap.set("n", "<C-h>", function() harpoon:list():select(1) end)
    vim.keymap.set("n", "<C-j>", function() harpoon:list():select(2) end)
  end,
  dependencies = {"nvim-lua/plenary.nvim",},
},
```

Every time I close nvim, the harpoon list dissapears. If I get back to the first version with my old config, it the list of harpoon files is back.

**Comment by ThePrimeagen** [comment] 2023-12-01 00:00
All right. Let me try it out, I will try it out tonight on stream

**Comment by ThePrimeagen** [comment] 2023-12-01 02:50
yes, all of the previous lists will disappear, @yobibyte are you able to persist after the switch over?

i think i could come up with a way to migrate data

**Comment by ThePrimeagen** [comment] 2023-12-01 02:50
also @sgoudham do you get persistent saves _after_ swapping to H2?  or are you unable to save all together?

**Comment by sgoudham** [comment] 2023-12-01 03:04
@ThePrimeagen I'm unable to keep persistent saves between opening and closing neovim.

I have a feeling that it may be another plugin causing this issue. I'll see if I can reproduce this tomorrow with no other plugins loaded 👍

**Comment by zachlankton** [comment] 2023-12-01 03:25
I think you are missing 

```lua
harpoon:setup()
```

When I add this, persistence works.

**Comment by ThePrimeagen** [comment] 2023-12-01 03:32
@sgoudham likely has nothing to do with other plugins.  i should have _no_ issues with other plugins

**Comment by ThePrimeagen** [comment] 2023-12-01 21:11
i assume this is fixed, reopen if its not!

**Closed by ThePrimeagen** 2023-12-01 21:11 UTC

**Comment by yobibyte** [comment] 2023-12-01 22:06
Can confirm that it was missing `harpoon:setup()` that caused the issue. I lost my old lists after h1 to h2 switch, but the h2 list is persistent now after closing/reopening nvim.

**Comment by ThePrimeagen** [comment] 2023-12-01 22:19
yes,i never wrote a h1 -> h2 list thing... because... well.. i don't think its worth the effort
