### ISSUE TITLE
Neovim 0.94 error when loading harpoon

### ISSUE THREAD

**Issue by tannerellen** [ThePrimeagen/harpoon#323] opened 2023-10-09 23:49 UTC
After updating to Neovim 0.94 I now get an error due to harpoon on launch...

Failed to run `config` for harpoon

...nner/.local/share/nvim/lazy/harpoon/lua/harpoon/init.lua:18: Invalid 'event': 'BufLeave, VimLeave'

# stacktrace:
  - /harpoon/lua/harpoon/init.lua:18
  - ~/.config/nvim/lua/plugins/init.lua:169 _in_ **config**
  - ~/.config/nvim/lua/core/lazy.lua:14
  - ~/.dotfiles/nvim/.config/nvim/init.lua:7

**Comment by OSITO326** [comment] 2023-10-10 00:44
same error here!

**Comment by miguelrincon1705** [comment] 2023-10-10 03:33
I have the same problem with the following environment: 
<img width="216" alt="image" src="https://github.com/ThePrimeagen/harpoon/assets/48895453/987ae967-7c85-47ef-af0f-b8a8c2f154e8">

**Comment by wookayin** [comment] 2023-10-10 05:26
will be fixed by #321

**Comment by mzndr** [comment] 2023-10-10 09:34
Can confirm that downgrading nvim to `0.9.2` fixes the issue. For anyone using pacman, you can downgrade by directly installing the older by file from cache, until the issue is resolved:
`sudo pacman -U /var/cache/pacman/pkg/neovim-0.9.2-1-x86_64.pkg.tar.zst`

**Comment by Yvey** [comment] 2023-10-10 10:03
Greetings, I am still new to Neovim.
I had the same issues when I was installing harpoon.

The error that I got is:
`Error detected while processing C:\Users\USer\AppData\Local\nvim\after\plugin\harpoon.lua:
E5113: Error while calling lua chunk: ...data\site\pack\packer\start\harpoon/lua/harpoon/init.lua:18: Invalid 'event': 'BufLeave, VimLeave'
stack traceback:
        [C]: in function 'nvim_create_autocmd'
        ...data\site\pack\packer\start\harpoon/lua/harpoon/init.lua:18: in main chunk
        [C]: in function 'require'
        ...data\site\pack\packer\start\harpoon/lua/harpoon/mark.lua:1: in main chunk
        [C]: in function 'require'
        C:\Users\User\AppData\Local\nvim\after\plugin\harpoon.lua:1: in main chunk`

**Comment by Yvey** [comment] 2023-10-10 10:09
Nevermind.
I got it fixed by adding `'` at line 18
in 
`...data\site\pack\packer\start\harpoon/lua/harpoon/init.lua`

from
`'BufLeave, VimLeave'`
to
`'BufLeave', 'VimLeave'`

**Comment by miguelrincon1705** [comment] 2023-10-10 11:41
I can confirm that going back to [nvim 0.9.2](https://github.com/neovim/neovim/releases/tag/v0.9.2) fixed the problem in ubuntu 22.04. Thanks! 💯

**Comment by ThePrimeagen** [comment] 2023-10-10 13:43
i am in the process of creating and writing harpoon 2,

if anyone wants to submit a small pr for this exact fix, i'll merge as a stop gap

**Closed** 2023-10-10 13:46 UTC
